### ISSUE TITLE
Request by FoolCraft DevTeam - Add Textures for Deprecated Blocks

### ISSUE THREAD

**Issue by Jo-Mamma75** [D-prog-55/ConcreteMod#5]
@D-prog-55 
I was asked by Iskall85 to contact you on behalf of the FoolCraft DevTeam (including myself, Scalda, CriticalMole and HazDS) as well as the Fools playing on the FoolCraft server (Iskall85, BDoubleO100, GoodTimesWithScar, Xisuma, etc) to ask you if it would be possible for you to add in textures to the deprecated blocks within your mod.  This change has had an absolutely devastating effect on their server due to the number of blocks of changed within Chisel & Bits and ArchitectureCraft being used with your concrete and will result in many, many hours of work.

If you would be willing to do this for us we would be immensely grateful.
Thank you in advance for your consideration and we look forward to hearing back from you.

Jo_Mamma75
Iskall85 Community Administrator
FoolCraft DevTeam

**Comment by D-prog-55** [comment]
Yeah, I didn't though of those kind of mods when I did those blocks.
I made them so you could transit from my old, ugly, one block per color system ('cause I couldn't get block states to work) to the new system.

_I will also rework more on the mod and it will require a utility mod I am writing._

But yeah, I will make a config where you can toggle off the "@ Deprecated this //**TODO**: fix" texture.

Also, I'm really pleased that you (the Fools) play with my mod.

**Comment by Jo-Mamma75** [comment]
Thank you so very much @D-prog-55 . We really appreciate it.

**Comment by scalda** [comment]
Hi, is there any update on this feature yet?

**Comment by D-prog-55** [comment]
I am working on the mod (literally, I'm progressively re-adding everything since I restarted from scratch). The config feature is done (will have to be set by the members as this is client-side) to switch between the Java pun model and the normal model.

If you want, I can upload a beta build of this version (you light loose some blocks as I did not re-implement all of them).

**Comment by D-prog-55** [comment]
Version 1.2 of the mod has been released. Tell all the Fools to set the config "useDeprecatedTextures" (under "client") to false to have the proper concrete models.

Also it requires a utility mod which is currently being approved, so I can't link it yet.

**Comment by scalda** [comment]
hey thanks for this i will test this out and hopefully push a 1.4.7 update of fool craft today

**Comment by scalda** [comment]
Server crash using your latest builds like i said i would. looks like it is trying to run client code on the server


[log](https://pastebin.com/DzwAhPsA)

**Comment by D-prog-55** [comment]
Should be fixed, the file is being approved.

**Comment by scalda** [comment]
Hi thanks for this I will test again once approved

**Comment by D-prog-55** [comment]
It's taking time to review it, so [here](http://dbrown55.ddns.net:8000/files/concreteMod-1.2.jar) it is.

**Comment by scalda** [comment]
Hi, i have finally got round to test this version and I'm still getting the crash on the server is it suppose to be 1.2 still on curse?

[crash](https://pastebin.com/xc713J1i)

**Comment by D-prog-55** [comment]
Now it should be working (under review).

**Comment by scalda** [comment]
another server crash with the version on curse that i just grabbed https://pastebin.com/DGrgPUKU

**Comment by D-prog-55** [comment]
Okay now it's fully working.

**Comment by scalda** [comment]
hey that version worked thanks
